package com.nguyenminhkhang.taskmanagement.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color


internal val bluePrimaryLight = Color(0xFF09677F)
internal val blueOnPrimaryLight = Color(0xFFFFFFFF)
internal val bluePrimaryContainerLight = Color(0xFFB8EAFF)
internal val blueOnPrimaryContainerLight = Color(0xFF004D61)
internal val blueSecondaryLight = Color(0xFF4C626B)
internal val blueOnSecondaryLight = Color(0xFFFFFFFF)
internal val blueSecondaryContainerLight = Color(0xFFCFE6F1)
internal val blueOnSecondaryContainerLight = Color(0xFF354A53)
internal val blueTertiaryLight = Color(0xFF08677F)
internal val blueOnTertiaryLight = Color(0xFFFFFFFF)
internal val blueTertiaryContainerLight = Color(0xFFB8EAFF)
internal val blueOnTertiaryContainerLight = Color(0xFF004D61)
internal val blueErrorLight = Color(0xFFBA1A1A)
internal val blueOnErrorLight = Color(0xFFFFFFFF)
internal val blueErrorContainerLight = Color(0xFFFFDAD6)
internal val blueOnErrorContainerLight = Color(0xFF93000A)
internal val blueBackgroundLight = Color(0xFFF5FAFD)
internal val blueOnBackgroundLight = Color(0xFF171C1F)
internal val blueSurfaceLight = Color(0xFFF5FAFD)
internal val blueOnSurfaceLight = Color(0xFF171C1F)
internal val blueSurfaceVariantLight = Color(0xFFDCE4E8)
internal val blueOnSurfaceVariantLight = Color(0xFF40484C)
internal val blueOutlineLight = Color(0xFF70787C)
internal val blueOutlineVariantLight = Color(0xFFBFC8CC)
internal val blueScrimLight = Color(0xFF000000)
internal val blueInverseSurfaceLight = Color(0xFF2C3134)
internal val blueInverseOnSurfaceLight = Color(0xFFEDF1F4)
internal val blueInversePrimaryLight = Color(0xFF88D0EC)
internal val blueSurfaceDimLight = Color(0xFFD6DBDE)
internal val blueSurfaceBrightLight = Color(0xFFF5FAFD)
internal val blueSurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val blueSurfaceContainerLowLight = Color(0xFFF0F4F7)
internal val blueSurfaceContainerLight = Color(0xFFEAEEF2)
internal val blueSurfaceContainerHighLight = Color(0xFFE4E9EC)
internal val blueSurfaceContainerHighestLight = Color(0xFFDEE3E6)

internal val bluePrimaryLightMediumContrast = Color(0xFF003C4B)
internal val blueOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val bluePrimaryContainerLightMediumContrast = Color(0xFF25768F)
internal val blueOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val blueSecondaryLightMediumContrast = Color(0xFF243942)
internal val blueOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val blueSecondaryContainerLightMediumContrast = Color(0xFF5B707A)
internal val blueOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val blueTertiaryLightMediumContrast = Color(0xFF003C4B)
internal val blueOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val blueTertiaryContainerLightMediumContrast = Color(0xFF25768F)
internal val blueOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val blueErrorLightMediumContrast = Color(0xFF740006)
internal val blueOnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val blueErrorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val blueOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val blueBackgroundLightMediumContrast = Color(0xFFF5FAFD)
internal val blueOnBackgroundLightMediumContrast = Color(0xFF171C1F)
internal val blueSurfaceLightMediumContrast = Color(0xFFF5FAFD)
internal val blueOnSurfaceLightMediumContrast = Color(0xFF0D1214)
internal val blueSurfaceVariantLightMediumContrast = Color(0xFFDCE4E8)
internal val blueOnSurfaceVariantLightMediumContrast = Color(0xFF2F373B)
internal val blueOutlineLightMediumContrast = Color(0xFF4C5458)
internal val blueOutlineVariantLightMediumContrast = Color(0xFF666E72)
internal val blueScrimLightMediumContrast = Color(0xFF000000)
internal val blueInverseSurfaceLightMediumContrast = Color(0xFF2C3134)
internal val blueInverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F4)
internal val blueInversePrimaryLightMediumContrast = Color(0xFF88D0EC)
internal val blueSurfaceDimLightMediumContrast = Color(0xFFC2C7CA)
internal val blueSurfaceBrightLightMediumContrast = Color(0xFFF5FAFD)
internal val blueSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val blueSurfaceContainerLowLightMediumContrast = Color(0xFFF0F4F7)
internal val blueSurfaceContainerLightMediumContrast = Color(0xFFE4E9EC)
internal val blueSurfaceContainerHighLightMediumContrast = Color(0xFFD9DDE1)
internal val blueSurfaceContainerHighestLightMediumContrast = Color(0xFFCDD2D5)

internal val bluePrimaryLightHighContrast = Color(0xFF00313E)
internal val blueOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val bluePrimaryContainerLightHighContrast = Color(0xFF005064)
internal val blueOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val blueSecondaryLightHighContrast = Color(0xFF192F37)
internal val blueOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val blueSecondaryContainerLightHighContrast = Color(0xFF374C55)
internal val blueOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val blueTertiaryLightHighContrast = Color(0xFF00313E)
internal val blueOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val blueTertiaryContainerLightHighContrast = Color(0xFF005064)
internal val blueOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val blueErrorLightHighContrast = Color(0xFF600004)
internal val blueOnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val blueErrorContainerLightHighContrast = Color(0xFF98000A)
internal val blueOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val blueBackgroundLightHighContrast = Color(0xFFF5FAFD)
internal val blueOnBackgroundLightHighContrast = Color(0xFF171C1F)
internal val blueSurfaceLightHighContrast = Color(0xFFF5FAFD)
internal val blueOnSurfaceLightHighContrast = Color(0xFF000000)
internal val blueSurfaceVariantLightHighContrast = Color(0xFFDCE4E8)
internal val blueOnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val blueOutlineLightHighContrast = Color(0xFF252D31)
internal val blueOutlineVariantLightHighContrast = Color(0xFF424A4E)
internal val blueScrimLightHighContrast = Color(0xFF000000)
internal val blueInverseSurfaceLightHighContrast = Color(0xFF2C3134)
internal val blueInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val blueInversePrimaryLightHighContrast = Color(0xFF88D0EC)
internal val blueSurfaceDimLightHighContrast = Color(0xFFB4B9BC)
internal val blueSurfaceBrightLightHighContrast = Color(0xFFF5FAFD)
internal val blueSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val blueSurfaceContainerLowLightHighContrast = Color(0xFFEDF1F4)
internal val blueSurfaceContainerLightHighContrast = Color(0xFFDEE3E6)
internal val blueSurfaceContainerHighLightHighContrast = Color(0xFFD0D5D8)
internal val blueSurfaceContainerHighestLightHighContrast = Color(0xFFC2C7CA)

internal val bluePrimaryDark = Color(0xFF88D0EC)
internal val blueOnPrimaryDark = Color(0xFF003544)
internal val bluePrimaryContainerDark = Color(0xFF004D61)
internal val blueOnPrimaryContainerDark = Color(0xFFB8EAFF)
internal val blueSecondaryDark = Color(0xFFB3CAD5)
internal val blueOnSecondaryDark = Color(0xFF1E333C)
internal val blueSecondaryContainerDark = Color(0xFF354A53)
internal val blueOnSecondaryContainerDark = Color(0xFFCFE6F1)
internal val blueTertiaryDark = Color(0xFF88D1EC)
internal val blueOnTertiaryDark = Color(0xFF003544)
internal val blueTertiaryContainerDark = Color(0xFF004D61)
internal val blueOnTertiaryContainerDark = Color(0xFFB8EAFF)
internal val blueErrorDark = Color(0xFFFFB4AB)
internal val blueOnErrorDark = Color(0xFF690005)
internal val blueErrorContainerDark = Color(0xFF93000A)
internal val blueOnErrorContainerDark = Color(0xFFFFDAD6)
internal val blueBackgroundDark = Color(0xFF0F1416)
internal val blueOnBackgroundDark = Color(0xFFDEE3E6)
internal val blueSurfaceDark = Color(0xFF0F1416)
internal val blueOnSurfaceDark = Color(0xFFDEE3E6)
internal val blueSurfaceVariantDark = Color(0xFF40484C)
internal val blueOnSurfaceVariantDark = Color(0xFFBFC8CC)
internal val blueOutlineDark = Color(0xFF8A9296)
internal val blueOutlineVariantDark = Color(0xFF40484C)
internal val blueScrimDark = Color(0xFF000000)
internal val blueInverseSurfaceDark = Color(0xFFDEE3E6)
internal val blueInverseOnSurfaceDark = Color(0xFF2C3134)
internal val blueInversePrimaryDark = Color(0xFF09677F)
internal val blueSurfaceDimDark = Color(0xFF0F1416)
internal val blueSurfaceBrightDark = Color(0xFF353A3D)
internal val blueSurfaceContainerLowestDark = Color(0xFF0A0F11)
internal val blueSurfaceContainerLowDark = Color(0xFF171C1F)
internal val blueSurfaceContainerDark = Color(0xFF1B2023)
internal val blueSurfaceContainerHighDark = Color(0xFF252B2D)
internal val blueSurfaceContainerHighestDark = Color(0xFF303638)

internal val bluePrimaryDarkMediumContrast = Color(0xFFA7E5FF)
internal val blueOnPrimaryDarkMediumContrast = Color(0xFF002A36)
internal val bluePrimaryContainerDarkMediumContrast = Color(0xFF509AB4)
internal val blueOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val blueSecondaryDarkMediumContrast = Color(0xFFC9E0EB)
internal val blueOnSecondaryDarkMediumContrast = Color(0xFF132830)
internal val blueSecondaryContainerDarkMediumContrast = Color(0xFF7E949E)
internal val blueOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val blueTertiaryDarkMediumContrast = Color(0xFFA6E6FF)
internal val blueOnTertiaryDarkMediumContrast = Color(0xFF002A35)
internal val blueTertiaryContainerDarkMediumContrast = Color(0xFF509AB4)
internal val blueOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val blueErrorDarkMediumContrast = Color(0xFFFFD2CC)
internal val blueOnErrorDarkMediumContrast = Color(0xFF540003)
internal val blueErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val blueOnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val blueBackgroundDarkMediumContrast = Color(0xFF0F1416)
internal val blueOnBackgroundDarkMediumContrast = Color(0xFFDEE3E6)
internal val blueSurfaceDarkMediumContrast = Color(0xFF0F1416)
internal val blueOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val blueSurfaceVariantDarkMediumContrast = Color(0xFF40484C)
internal val blueOnSurfaceVariantDarkMediumContrast = Color(0xFFD5DEE2)
internal val blueOutlineDarkMediumContrast = Color(0xFFABB3B7)
internal val blueOutlineVariantDarkMediumContrast = Color(0xFF899296)
internal val blueScrimDarkMediumContrast = Color(0xFF000000)
internal val blueInverseSurfaceDarkMediumContrast = Color(0xFFDEE3E6)
internal val blueInverseOnSurfaceDarkMediumContrast = Color(0xFF252B2D)
internal val blueInversePrimaryDarkMediumContrast = Color(0xFF004F63)
internal val blueSurfaceDimDarkMediumContrast = Color(0xFF0F1416)
internal val blueSurfaceBrightDarkMediumContrast = Color(0xFF404548)
internal val blueSurfaceContainerLowestDarkMediumContrast = Color(0xFF04080A)
internal val blueSurfaceContainerLowDarkMediumContrast = Color(0xFF191E21)
internal val blueSurfaceContainerDarkMediumContrast = Color(0xFF23292B)
internal val blueSurfaceContainerHighDarkMediumContrast = Color(0xFF2E3336)
internal val blueSurfaceContainerHighestDarkMediumContrast = Color(0xFF393E41)

internal val bluePrimaryDarkHighContrast = Color(0xFFDCF4FF)
internal val blueOnPrimaryDarkHighContrast = Color(0xFF000000)
internal val bluePrimaryContainerDarkHighContrast = Color(0xFF84CDE8)
internal val blueOnPrimaryContainerDarkHighContrast = Color(0xFF000D13)
internal val blueSecondaryDarkHighContrast = Color(0xFFDCF4FF)
internal val blueOnSecondaryDarkHighContrast = Color(0xFF000000)
internal val blueSecondaryContainerDarkHighContrast = Color(0xFFAFC6D1)
internal val blueOnSecondaryContainerDarkHighContrast = Color(0xFF000D13)
internal val blueTertiaryDarkHighContrast = Color(0xFFDBF4FF)
internal val blueOnTertiaryDarkHighContrast = Color(0xFF000000)
internal val blueTertiaryContainerDarkHighContrast = Color(0xFF84CDE8)
internal val blueOnTertiaryContainerDarkHighContrast = Color(0xFF000D13)
internal val blueErrorDarkHighContrast = Color(0xFFFFECE9)
internal val blueOnErrorDarkHighContrast = Color(0xFF000000)
internal val blueErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val blueOnErrorContainerDarkHighContrast = Color(0xFF220001)
internal val blueBackgroundDarkHighContrast = Color(0xFF0F1416)
internal val blueOnBackgroundDarkHighContrast = Color(0xFFDEE3E6)
internal val blueSurfaceDarkHighContrast = Color(0xFF0F1416)
internal val blueOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val blueSurfaceVariantDarkHighContrast = Color(0xFF40484C)
internal val blueOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val blueOutlineDarkHighContrast = Color(0xFFE9F1F6)
internal val blueOutlineVariantDarkHighContrast = Color(0xFFBCC4C8)
internal val blueScrimDarkHighContrast = Color(0xFF000000)
internal val blueInverseSurfaceDarkHighContrast = Color(0xFFDEE3E6)
internal val blueInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val blueInversePrimaryDarkHighContrast = Color(0xFF004F63)
internal val blueSurfaceDimDarkHighContrast = Color(0xFF0F1416)
internal val blueSurfaceBrightDarkHighContrast = Color(0xFF4B5154)
internal val blueSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val blueSurfaceContainerLowDarkHighContrast = Color(0xFF1B2023)
internal val blueSurfaceContainerDarkHighContrast = Color(0xFF2C3134)
internal val blueSurfaceContainerHighDarkHighContrast = Color(0xFF373C3F)
internal val blueSurfaceContainerHighestDarkHighContrast = Color(0xFF42484A)









internal val BlueLightColorScheme = lightColorScheme(

    primary = bluePrimaryLight,
    onPrimary = blueOnPrimaryLight,
    primaryContainer = bluePrimaryContainerLight,
    onPrimaryContainer = blueOnPrimaryContainerLight,
    secondary = blueSecondaryLight,
    onSecondary = blueOnSecondaryLight,
    secondaryContainer = blueSecondaryContainerLight,
    onSecondaryContainer = blueOnSecondaryContainerLight,
    tertiary = blueTertiaryLight,
    onTertiary = blueOnTertiaryLight,
    tertiaryContainer = blueTertiaryContainerLight,
    onTertiaryContainer = blueOnTertiaryContainerLight,
    error = blueErrorLight,
    onError = blueOnErrorLight,
    errorContainer = blueErrorContainerLight,
    onErrorContainer = blueOnErrorContainerLight,
    background = blueBackgroundLight,
    onBackground = blueOnBackgroundLight,
    surface = blueSurfaceLight,
    onSurface = blueOnSurfaceLight,
    surfaceVariant = blueSurfaceVariantLight,
    onSurfaceVariant = blueOnSurfaceVariantLight,
    outline = blueOutlineLight,
    outlineVariant = blueOutlineVariantLight,
    scrim = blueScrimLight,
    inverseSurface = blueInverseSurfaceLight,
    inverseOnSurface = blueInverseOnSurfaceLight,
    inversePrimary = blueInversePrimaryLight,
    surfaceDim = blueSurfaceDimLight,
    surfaceBright = blueSurfaceBrightLight,
    surfaceContainerLowest = blueSurfaceContainerLowestLight,
    surfaceContainerLow = blueSurfaceContainerLowLight,
    surfaceContainer = blueSurfaceContainerLight,
    surfaceContainerHigh = blueSurfaceContainerHighLight,
    surfaceContainerHighest = blueSurfaceContainerHighestLight,

)

internal val BlueDarkColorScheme = darkColorScheme(

    primary = bluePrimaryDark,
    onPrimary = blueOnPrimaryDark,
    primaryContainer = bluePrimaryContainerDark,
    onPrimaryContainer = blueOnPrimaryContainerDark,
    secondary = blueSecondaryDark,
    onSecondary = blueOnSecondaryDark,
    secondaryContainer = blueSecondaryContainerDark,
    onSecondaryContainer = blueOnSecondaryContainerDark,
    tertiary = blueTertiaryDark,
    onTertiary = blueOnTertiaryDark,
    tertiaryContainer = blueTertiaryContainerDark,
    onTertiaryContainer = blueOnTertiaryContainerDark,
    error = blueErrorDark,
    onError = blueOnErrorDark,
    errorContainer = blueErrorContainerDark,
    onErrorContainer = blueOnErrorContainerDark,
    background = blueBackgroundDark,
    onBackground = blueOnBackgroundDark,
    surface = blueSurfaceDark,
    onSurface = blueOnSurfaceDark,
    surfaceVariant = blueSurfaceVariantDark,
    onSurfaceVariant = blueOnSurfaceVariantDark,
    outline = blueOutlineDark,
    outlineVariant = blueOutlineVariantDark,
    scrim = blueScrimDark,
    inverseSurface = blueInverseSurfaceDark,
    inverseOnSurface = blueInverseOnSurfaceDark,
    inversePrimary = blueInversePrimaryDark,
    surfaceDim = blueSurfaceDimDark,
    surfaceBright = blueSurfaceBrightDark,
    surfaceContainerLowest = blueSurfaceContainerLowestDark,
    surfaceContainerLow = blueSurfaceContainerLowDark,
    surfaceContainer = blueSurfaceContainerDark,
    surfaceContainerHigh = blueSurfaceContainerHighDark,
    surfaceContainerHighest = blueSurfaceContainerHighestDark,

)
