package com.nguyenminhkhang.taskmanagement.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color


internal val greenPrimaryLight = Color(0xFF6D5E0F)
internal val greenOnPrimaryLight = Color(0xFFFFFFFF)
internal val greenPrimaryContainerLight = Color(0xFFF8E287)
internal val greenOnPrimaryContainerLight = Color(0xFF534600)
internal val greenSecondaryLight = Color(0xFF665E40)
internal val greenOnSecondaryLight = Color(0xFFFFFFFF)
internal val greenSecondaryContainerLight = Color(0xFFEEE2BC)
internal val greenOnSecondaryContainerLight = Color(0xFF4E472A)
internal val greenTertiaryLight = Color(0xFF43664E)
internal val greenOnTertiaryLight = Color(0xFFFFFFFF)
internal val greenTertiaryContainerLight = Color(0xFFC5ECCE)
internal val greenOnTertiaryContainerLight = Color(0xFF2C4E38)
internal val greenErrorLight = Color(0xFFBA1A1A)
internal val greenOnErrorLight = Color(0xFFFFFFFF)
internal val greenErrorContainerLight = Color(0xFFFFDAD6)
internal val greenOnErrorContainerLight = Color(0xFF93000A)
internal val greenBackgroundLight = Color(0xFFFFF9EE)
internal val greenOnBackgroundLight = Color(0xFF1E1B13)
internal val greenSurfaceLight = Color(0xFFFFF9EE)
internal val greenOnSurfaceLight = Color(0xFF1E1B13)
internal val greenSurfaceVariantLight = Color(0xFFEAE2D0)
internal val greenOnSurfaceVariantLight = Color(0xFF4B4739)
internal val greenOutlineLight = Color(0xFF7C7767)
internal val greenOutlineVariantLight = Color(0xFFCDC6B4)
internal val greenScrimLight = Color(0xFF000000)
internal val greenInverseSurfaceLight = Color(0xFF333027)
internal val greenInverseOnSurfaceLight = Color(0xFFF7F0E2)
internal val greenInversePrimaryLight = Color(0xFFDBC66E)
internal val greenSurfaceDimLight = Color(0xFFE0D9CC)
internal val greenSurfaceBrightLight = Color(0xFFFFF9EE)
internal val greenSurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val greenSurfaceContainerLowLight = Color(0xFFFAF3E5)
internal val greenSurfaceContainerLight = Color(0xFFF4EDDF)
internal val greenSurfaceContainerHighLight = Color(0xFFEEE8DA)
internal val greenSurfaceContainerHighestLight = Color(0xFFE8E2D4)

internal val greenPrimaryLightMediumContrast = Color(0xFF403600)
internal val greenOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val greenPrimaryContainerLightMediumContrast = Color(0xFF7D6C1E)
internal val greenOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val greenSecondaryLightMediumContrast = Color(0xFF3C361B)
internal val greenOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val greenSecondaryContainerLightMediumContrast = Color(0xFF756D4E)
internal val greenOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val greenTertiaryLightMediumContrast = Color(0xFF1B3D28)
internal val greenOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val greenTertiaryContainerLightMediumContrast = Color(0xFF52755D)
internal val greenOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val greenErrorLightMediumContrast = Color(0xFF740006)
internal val greenOnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val greenErrorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val greenOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val greenBackgroundLightMediumContrast = Color(0xFFFFF9EE)
internal val greenOnBackgroundLightMediumContrast = Color(0xFF1E1B13)
internal val greenSurfaceLightMediumContrast = Color(0xFFFFF9EE)
internal val greenOnSurfaceLightMediumContrast = Color(0xFF131109)
internal val greenSurfaceVariantLightMediumContrast = Color(0xFFEAE2D0)
internal val greenOnSurfaceVariantLightMediumContrast = Color(0xFF3A3629)
internal val greenOutlineLightMediumContrast = Color(0xFF575244)
internal val greenOutlineVariantLightMediumContrast = Color(0xFF726D5E)
internal val greenScrimLightMediumContrast = Color(0xFF000000)
internal val greenInverseSurfaceLightMediumContrast = Color(0xFF333027)
internal val greenInverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
internal val greenInversePrimaryLightMediumContrast = Color(0xFFDBC66E)
internal val greenSurfaceDimLightMediumContrast = Color(0xFFCCC6B9)
internal val greenSurfaceBrightLightMediumContrast = Color(0xFFFFF9EE)
internal val greenSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val greenSurfaceContainerLowLightMediumContrast = Color(0xFFFAF3E5)
internal val greenSurfaceContainerLightMediumContrast = Color(0xFFEEE8DA)
internal val greenSurfaceContainerHighLightMediumContrast = Color(0xFFE3DCCF)
internal val greenSurfaceContainerHighestLightMediumContrast = Color(0xFFD7D1C4)

internal val greenPrimaryLightHighContrast = Color(0xFF352C00)
internal val greenOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val greenPrimaryContainerLightHighContrast = Color(0xFF564800)
internal val greenOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val greenSecondaryLightHighContrast = Color(0xFF322C12)
internal val greenOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val greenSecondaryContainerLightHighContrast = Color(0xFF50492D)
internal val greenOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val greenTertiaryLightHighContrast = Color(0xFF10321F)
internal val greenOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val greenTertiaryContainerLightHighContrast = Color(0xFF2E503A)
internal val greenOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val greenErrorLightHighContrast = Color(0xFF600004)
internal val greenOnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val greenErrorContainerLightHighContrast = Color(0xFF98000A)
internal val greenOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val greenBackgroundLightHighContrast = Color(0xFFFFF9EE)
internal val greenOnBackgroundLightHighContrast = Color(0xFF1E1B13)
internal val greenSurfaceLightHighContrast = Color(0xFFFFF9EE)
internal val greenOnSurfaceLightHighContrast = Color(0xFF000000)
internal val greenSurfaceVariantLightHighContrast = Color(0xFFEAE2D0)
internal val greenOnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val greenOutlineLightHighContrast = Color(0xFF2F2C20)
internal val greenOutlineVariantLightHighContrast = Color(0xFF4D493B)
internal val greenScrimLightHighContrast = Color(0xFF000000)
internal val greenInverseSurfaceLightHighContrast = Color(0xFF333027)
internal val greenInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val greenInversePrimaryLightHighContrast = Color(0xFFDBC66E)
internal val greenSurfaceDimLightHighContrast = Color(0xFFBEB8AB)
internal val greenSurfaceBrightLightHighContrast = Color(0xFFFFF9EE)
internal val greenSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val greenSurfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
internal val greenSurfaceContainerLightHighContrast = Color(0xFFE8E2D4)
internal val greenSurfaceContainerHighLightHighContrast = Color(0xFFDAD4C6)
internal val greenSurfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

internal val greenPrimaryDark = Color(0xFFDBC66E)
internal val greenOnPrimaryDark = Color(0xFF3A3000)
internal val greenPrimaryContainerDark = Color(0xFF534600)
internal val greenOnPrimaryContainerDark = Color(0xFFF8E287)
internal val greenSecondaryDark = Color(0xFFD1C6A1)
internal val greenOnSecondaryDark = Color(0xFF363016)
internal val greenSecondaryContainerDark = Color(0xFF4E472A)
internal val greenOnSecondaryContainerDark = Color(0xFFEEE2BC)
internal val greenTertiaryDark = Color(0xFFA9D0B3)
internal val greenOnTertiaryDark = Color(0xFF143723)
internal val greenTertiaryContainerDark = Color(0xFF2C4E38)
internal val greenOnTertiaryContainerDark = Color(0xFFC5ECCE)
internal val greenErrorDark = Color(0xFFFFB4AB)
internal val greenOnErrorDark = Color(0xFF690005)
internal val greenErrorContainerDark = Color(0xFF93000A)
internal val greenOnErrorContainerDark = Color(0xFFFFDAD6)
internal val greenBackgroundDark = Color(0xFF15130B)
internal val greenOnBackgroundDark = Color(0xFFE8E2D4)
internal val greenSurfaceDark = Color(0xFF15130B)
internal val greenOnSurfaceDark = Color(0xFFE8E2D4)
internal val greenSurfaceVariantDark = Color(0xFF4B4739)
internal val greenOnSurfaceVariantDark = Color(0xFFCDC6B4)
internal val greenOutlineDark = Color(0xFF969080)
internal val greenOutlineVariantDark = Color(0xFF4B4739)
internal val greenScrimDark = Color(0xFF000000)
internal val greenInverseSurfaceDark = Color(0xFFE8E2D4)
internal val greenInverseOnSurfaceDark = Color(0xFF333027)
internal val greenInversePrimaryDark = Color(0xFF6D5E0F)
internal val greenSurfaceDimDark = Color(0xFF15130B)
internal val greenSurfaceBrightDark = Color(0xFF3C3930)
internal val greenSurfaceContainerLowestDark = Color(0xFF100E07)
internal val greenSurfaceContainerLowDark = Color(0xFF1E1B13)
internal val greenSurfaceContainerDark = Color(0xFF222017)
internal val greenSurfaceContainerHighDark = Color(0xFF2D2A21)
internal val greenSurfaceContainerHighestDark = Color(0xFF38352B)

internal val greenPrimaryDarkMediumContrast = Color(0xFFF2DC82)
internal val greenOnPrimaryDarkMediumContrast = Color(0xFF2D2500)
internal val greenPrimaryContainerDarkMediumContrast = Color(0xFFA3903F)
internal val greenOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val greenSecondaryDarkMediumContrast = Color(0xFFE8DCB6)
internal val greenOnSecondaryDarkMediumContrast = Color(0xFF2B250C)
internal val greenSecondaryContainerDarkMediumContrast = Color(0xFF9A916F)
internal val greenOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val greenTertiaryDarkMediumContrast = Color(0xFFBFE6C8)
internal val greenOnTertiaryDarkMediumContrast = Color(0xFF082C18)
internal val greenTertiaryContainerDarkMediumContrast = Color(0xFF75997F)
internal val greenOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val greenErrorDarkMediumContrast = Color(0xFFFFD2CC)
internal val greenOnErrorDarkMediumContrast = Color(0xFF540003)
internal val greenErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val greenOnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val greenBackgroundDarkMediumContrast = Color(0xFF15130B)
internal val greenOnBackgroundDarkMediumContrast = Color(0xFFE8E2D4)
internal val greenSurfaceDarkMediumContrast = Color(0xFF15130B)
internal val greenOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val greenSurfaceVariantDarkMediumContrast = Color(0xFF4B4739)
internal val greenOnSurfaceVariantDarkMediumContrast = Color(0xFFE3DCCA)
internal val greenOutlineDarkMediumContrast = Color(0xFFB8B1A0)
internal val greenOutlineVariantDarkMediumContrast = Color(0xFF969080)
internal val greenScrimDarkMediumContrast = Color(0xFF000000)
internal val greenInverseSurfaceDarkMediumContrast = Color(0xFFE8E2D4)
internal val greenInverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
internal val greenInversePrimaryDarkMediumContrast = Color(0xFF554700)
internal val greenSurfaceDimDarkMediumContrast = Color(0xFF15130B)
internal val greenSurfaceBrightDarkMediumContrast = Color(0xFF48443A)
internal val greenSurfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
internal val greenSurfaceContainerLowDarkMediumContrast = Color(0xFF201D15)
internal val greenSurfaceContainerDarkMediumContrast = Color(0xFF2A281F)
internal val greenSurfaceContainerHighDarkMediumContrast = Color(0xFF353229)
internal val greenSurfaceContainerHighestDarkMediumContrast = Color(0xFF413D34)

internal val greenPrimaryDarkHighContrast = Color(0xFFFFF0BA)
internal val greenOnPrimaryDarkHighContrast = Color(0xFF000000)
internal val greenPrimaryContainerDarkHighContrast = Color(0xFFD7C26B)
internal val greenOnPrimaryContainerDarkHighContrast = Color(0xFF0F0B00)
internal val greenSecondaryDarkHighContrast = Color(0xFFFCF0C9)
internal val greenOnSecondaryDarkHighContrast = Color(0xFF000000)
internal val greenSecondaryContainerDarkHighContrast = Color(0xFFCDC29E)
internal val greenOnSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
internal val greenTertiaryDarkHighContrast = Color(0xFFD2FADB)
internal val greenOnTertiaryDarkHighContrast = Color(0xFF000000)
internal val greenTertiaryContainerDarkHighContrast = Color(0xFFA5CCAF)
internal val greenOnTertiaryContainerDarkHighContrast = Color(0xFF000F05)
internal val greenErrorDarkHighContrast = Color(0xFFFFECE9)
internal val greenOnErrorDarkHighContrast = Color(0xFF000000)
internal val greenErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val greenOnErrorContainerDarkHighContrast = Color(0xFF220001)
internal val greenBackgroundDarkHighContrast = Color(0xFF15130B)
internal val greenOnBackgroundDarkHighContrast = Color(0xFFE8E2D4)
internal val greenSurfaceDarkHighContrast = Color(0xFF15130B)
internal val greenOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val greenSurfaceVariantDarkHighContrast = Color(0xFF4B4739)
internal val greenOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val greenOutlineDarkHighContrast = Color(0xFFF7EFDD)
internal val greenOutlineVariantDarkHighContrast = Color(0xFFC9C2B1)
internal val greenScrimDarkHighContrast = Color(0xFF000000)
internal val greenInverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
internal val greenInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val greenInversePrimaryDarkHighContrast = Color(0xFF554700)
internal val greenSurfaceDimDarkHighContrast = Color(0xFF15130B)
internal val greenSurfaceBrightDarkHighContrast = Color(0xFF535046)
internal val greenSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val greenSurfaceContainerLowDarkHighContrast = Color(0xFF222017)
internal val greenSurfaceContainerDarkHighContrast = Color(0xFF333027)
internal val greenSurfaceContainerHighDarkHighContrast = Color(0xFF3E3B32)
internal val greenSurfaceContainerHighestDarkHighContrast = Color(0xFF4A473D)









internal val GreenLightColorScheme = lightColorScheme(

    primary = greenPrimaryLight,
    onPrimary = greenOnPrimaryLight,
    primaryContainer = greenPrimaryContainerLight,
    onPrimaryContainer = greenOnPrimaryContainerLight,
    secondary = greenSecondaryLight,
    onSecondary = greenOnSecondaryLight,
    secondaryContainer = greenSecondaryContainerLight,
    onSecondaryContainer = greenOnSecondaryContainerLight,
    tertiary = greenTertiaryLight,
    onTertiary = greenOnTertiaryLight,
    tertiaryContainer = greenTertiaryContainerLight,
    onTertiaryContainer = greenOnTertiaryContainerLight,
    error = greenErrorLight,
    onError = greenOnErrorLight,
    errorContainer = greenErrorContainerLight,
    onErrorContainer = greenOnErrorContainerLight,
    background = greenBackgroundLight,
    onBackground = greenOnBackgroundLight,
    surface = greenSurfaceLight,
    onSurface = greenOnSurfaceLight,
    surfaceVariant = greenSurfaceVariantLight,
    onSurfaceVariant = greenOnSurfaceVariantLight,
    outline = greenOutlineLight,
    outlineVariant = greenOutlineVariantLight,
    scrim = greenScrimLight,
    inverseSurface = greenInverseSurfaceLight,
    inverseOnSurface = greenInverseOnSurfaceLight,
    inversePrimary = greenInversePrimaryLight,
    surfaceDim = greenSurfaceDimLight,
    surfaceBright = greenSurfaceBrightLight,
    surfaceContainerLowest = greenSurfaceContainerLowestLight,
    surfaceContainerLow = greenSurfaceContainerLowLight,
    surfaceContainer = greenSurfaceContainerLight,
    surfaceContainerHigh = greenSurfaceContainerHighLight,
    surfaceContainerHighest = greenSurfaceContainerHighestLight,

)

internal val GreenDarkColorScheme = darkColorScheme(

    primary = greenPrimaryDark,
    onPrimary = greenOnPrimaryDark,
    primaryContainer = greenPrimaryContainerDark,
    onPrimaryContainer = greenOnPrimaryContainerDark,
    secondary = greenSecondaryDark,
    onSecondary = greenOnSecondaryDark,
    secondaryContainer = greenSecondaryContainerDark,
    onSecondaryContainer = greenOnSecondaryContainerDark,
    tertiary = greenTertiaryDark,
    onTertiary = greenOnTertiaryDark,
    tertiaryContainer = greenTertiaryContainerDark,
    onTertiaryContainer = greenOnTertiaryContainerDark,
    error = greenErrorDark,
    onError = greenOnErrorDark,
    errorContainer = greenErrorContainerDark,
    onErrorContainer = greenOnErrorContainerDark,
    background = greenBackgroundDark,
    onBackground = greenOnBackgroundDark,
    surface = greenSurfaceDark,
    onSurface = greenOnSurfaceDark,
    surfaceVariant = greenSurfaceVariantDark,
    onSurfaceVariant = greenOnSurfaceVariantDark,
    outline = greenOutlineDark,
    outlineVariant = greenOutlineVariantDark,
    scrim = greenScrimDark,
    inverseSurface = greenInverseSurfaceDark,
    inverseOnSurface = greenInverseOnSurfaceDark,
    inversePrimary = greenInversePrimaryDark,
    surfaceDim = greenSurfaceDimDark,
    surfaceBright = greenSurfaceBrightDark,
    surfaceContainerLowest = greenSurfaceContainerLowestDark,
    surfaceContainerLow = greenSurfaceContainerLowDark,
    surfaceContainer = greenSurfaceContainerDark,
    surfaceContainerHigh = greenSurfaceContainerHighDark,
    surfaceContainerHighest = greenSurfaceContainerHighestDark,

)
