package com.nguyeminhkhang.compose

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// --- Light Scheme ---
internal val orangePrimaryLight = Color(0xFF8B5000)
internal val orangeOnPrimaryLight = Color(0xFFFFFFFF)
internal val orangePrimaryContainerLight = Color(0xFFFFDCC0)
internal val orangeOnPrimaryContainerLight = Color(0xFF2D1600)
internal val orangeSecondaryLight = Color(0xFF715A41)
internal val orangeOnSecondaryLight = Color(0xFFFFFFFF)
internal val orangeSecondaryContainerLight = Color(0xFFFDDABE)
internal val orangeOnSecondaryContainerLight = Color(0xFF291805)
internal val orangeTertiaryLight = Color(0xFF54633D)
internal val orangeOnTertiaryLight = Color(0xFFFFFFFF)
internal val orangeTertiaryContainerLight = Color(0xFFD7E8BB)
internal val orangeOnTertiaryContainerLight = Color(0xFF121F03)
internal val orangeErrorLight = Color(0xFFBA1A1A)
internal val orangeOnErrorLight = Color(0xFFFFFFFF)
internal val orangeErrorContainerLight = Color(0xFFFFDAD6)
internal val orangeOnErrorContainerLight = Color(0xFF410002)
internal val orangeBackgroundLight = Color(0xFFFFF8F5)
internal val orangeOnBackgroundLight = Color(0xFF221A14)
internal val orangeSurfaceLight = Color(0xFFFFF8F5)
internal val orangeOnSurfaceLight = Color(0xFF221A14)
internal val orangeSurfaceVariantLight = Color(0xFFF1E0D0)
internal val orangeOnSurfaceVariantLight = Color(0xFF504539)
internal val orangeOutlineLight = Color(0xFF827568)
internal val orangeOutlineVariantLight = Color(0xFFD4C4B5)
internal val orangeScrimLight = Color(0xFF000000)
internal val orangeInverseSurfaceLight = Color(0xFF372F28)
internal val orangeInverseOnSurfaceLight = Color(0xFFFEEFE4)
internal val orangeInversePrimaryLight = Color(0xFFFFB879)
internal val orangeSurfaceDimLight = Color(0xFFE5D8CD)
internal val orangeSurfaceBrightLight = Color(0xFFFFF8F5)
internal val orangeSurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val orangeSurfaceContainerLowLight = Color(0xFFFFF1E8)
internal val orangeSurfaceContainerLight = Color(0xFFF9EBE1)
internal val orangeSurfaceContainerHighLight = Color(0xFFF4E5DB)
internal val orangeSurfaceContainerHighestLight = Color(0xFFEEE0D5)

// --- Medium Contrast Light ---
internal val orangePrimaryLightMediumContrast = Color(0xFF673A00)
internal val orangeOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val orangePrimaryContainerLightMediumContrast = Color(0xFFA86200)
internal val orangeOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeSecondaryLightMediumContrast = Color(0xFF533F28)
internal val orangeOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeSecondaryContainerLightMediumContrast = Color(0xFF897056)
internal val orangeOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeTertiaryLightMediumContrast = Color(0xFF384723)
internal val orangeOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeTertiaryContainerLightMediumContrast = Color(0xFF6A7951)
internal val orangeOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeErrorLightMediumContrast = Color(0xFF8C0009)
internal val orangeOnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeErrorContainerLightMediumContrast = Color(0xFFDA342E)
internal val orangeOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeBackgroundLightMediumContrast = Color(0xFFFFF8F5)
internal val orangeOnBackgroundLightMediumContrast = Color(0xFF221A14)
internal val orangeSurfaceLightMediumContrast = Color(0xFFFFF8F5)
internal val orangeOnSurfaceLightMediumContrast = Color(0xFF160F09)
internal val orangeSurfaceVariantLightMediumContrast = Color(0xFFF1E0D0)
internal val orangeOnSurfaceVariantLightMediumContrast = Color(0xFF3F3429)
internal val orangeOutlineLightMediumContrast = Color(0xFF5D5144)
internal val orangeOutlineVariantLightMediumContrast = Color(0xFF796D5F)
internal val orangeScrimLightMediumContrast = Color(0xFF000000)
internal val orangeInverseSurfaceLightMediumContrast = Color(0xFF372F28)
internal val orangeInverseOnSurfaceLightMediumContrast = Color(0xFFFEEFE4)
internal val orangeInversePrimaryLightMediumContrast = Color(0xFFFFB879)
internal val orangeSurfaceDimLightMediumContrast = Color(0xFFD1C4BA)
internal val orangeSurfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
internal val orangeSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val orangeSurfaceContainerLowLightMediumContrast = Color(0xFFFFF1E8)
internal val orangeSurfaceContainerLightMediumContrast = Color(0xFFF4E5DB)
internal val orangeSurfaceContainerHighLightMediumContrast = Color(0xFFE8D9D0)
internal val orangeSurfaceContainerHighestLightMediumContrast = Color(0xFFDCCDC5)

// --- High Contrast Light ---
internal val orangePrimaryLightHighContrast = Color(0xFF371C00)
internal val orangeOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val orangePrimaryContainerLightHighContrast = Color(0xFF673A00)
internal val orangeOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val orangeSecondaryLightHighContrast = Color(0xFF2F1F0A)
internal val orangeOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val orangeSecondaryContainerLightHighContrast = Color(0xFF533F28)
internal val orangeOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val orangeTertiaryLightHighContrast = Color(0xFF182506)
internal val orangeOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val orangeTertiaryContainerLightHighContrast = Color(0xFF384723)
internal val orangeOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val orangeErrorLightHighContrast = Color(0xFF4E0002)
internal val orangeOnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val orangeErrorContainerLightHighContrast = Color(0xFF8C0009)
internal val orangeOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val orangeBackgroundLightHighContrast = Color(0xFFFFF8F5)
internal val orangeOnBackgroundLightHighContrast = Color(0xFF221A14)
internal val orangeSurfaceLightHighContrast = Color(0xFFFFF8F5)
internal val orangeOnSurfaceLightHighContrast = Color(0xFF000000)
internal val orangeSurfaceVariantLightHighContrast = Color(0xFFF1E0D0)
internal val orangeOnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val orangeOutlineLightHighContrast = Color(0xFF33291F)
internal val orangeOutlineVariantLightHighContrast = Color(0xFF504539)
internal val orangeScrimLightHighContrast = Color(0xFF000000)
internal val orangeInverseSurfaceLightHighContrast = Color(0xFF372F28)
internal val orangeInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val orangeInversePrimaryLightHighContrast = Color(0xFFFFB879)
internal val orangeSurfaceDimLightHighContrast = Color(0xFFC3B6AC)
internal val orangeSurfaceBrightLightHighContrast = Color(0xFFFFF8F5)
internal val orangeSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val orangeSurfaceContainerLowLightHighContrast = Color(0xFFFEEFE4)
internal val orangeSurfaceContainerLightHighContrast = Color(0xFFEEE0D5)
internal val orangeSurfaceContainerHighLightHighContrast = Color(0xFFDECFC5)
internal val orangeSurfaceContainerHighestLightHighContrast = Color(0xFFD1C4BA)

// --- Dark Scheme ---
internal val orangePrimaryDark = Color(0xFFFFB879)
internal val orangeOnPrimaryDark = Color(0xFF4A2800)
internal val orangePrimaryContainerDark = Color(0xFF693C00)
internal val orangeOnPrimaryContainerDark = Color(0xFFFFDCC0)
internal val orangeSecondaryDark = Color(0xFFDFC0A3)
internal val orangeOnSecondaryDark = Color(0xFF3F2D17)
internal val orangeSecondaryContainerDark = Color(0xFF58432C)
internal val orangeOnSecondaryContainerDark = Color(0xFFFDDABE)
internal val orangeTertiaryDark = Color(0xFFBBCD9F)
internal val orangeOnTertiaryDark = Color(0xFF273513)
internal val orangeTertiaryContainerDark = Color(0xFF3D4B27)
internal val orangeOnTertiaryContainerDark = Color(0xFFD7E8BB)
internal val orangeErrorDark = Color(0xFFFFB4AB)
internal val orangeOnErrorDark = Color(0xFF690005)
internal val orangeErrorContainerDark = Color(0xFF93000A)
internal val orangeOnErrorContainerDark = Color(0xFFFFDAD6)
internal val orangeBackgroundDark = Color(0xFF19120C)
internal val orangeOnBackgroundDark = Color(0xFFEEE0D5)
internal val orangeSurfaceDark = Color(0xFF19120C)
internal val orangeOnSurfaceDark = Color(0xFFEEE0D5)
internal val orangeSurfaceVariantDark = Color(0xFF504539)
internal val orangeOnSurfaceVariantDark = Color(0xFFD4C4B5)
internal val orangeOutlineDark = Color(0xFF9C8E81)
internal val orangeOutlineVariantDark = Color(0xFF504539)
internal val orangeScrimDark = Color(0xFF000000)
internal val orangeInverseSurfaceDark = Color(0xFFEEE0D5)
internal val orangeInverseOnSurfaceDark = Color(0xFF372F28)
internal val orangeInversePrimaryDark = Color(0xFF8B5000)
internal val orangeSurfaceDimDark = Color(0xFF19120C)
internal val orangeSurfaceBrightDark = Color(0xFF413831)
internal val orangeSurfaceContainerLowestDark = Color(0xFF140D08)
internal val orangeSurfaceContainerLowDark = Color(0xFF221A14)
internal val orangeSurfaceContainerDark = Color(0xFF261E18)
internal val orangeSurfaceContainerHighDark = Color(0xFF312822)
internal val orangeSurfaceContainerHighestDark = Color(0xFF3C332C)

// --- Medium Contrast Dark ---
internal val orangePrimaryDarkMediumContrast = Color(0xFFFFC28F)
internal val orangeOnPrimaryDarkMediumContrast = Color(0xFF251100)
internal val orangePrimaryContainerDarkMediumContrast = Color(0xFFC97800)
internal val orangeOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val orangeSecondaryDarkMediumContrast = Color(0xFFE4C5A7)
internal val orangeOnSecondaryDarkMediumContrast = Color(0xFF231404)
internal val orangeSecondaryContainerDarkMediumContrast = Color(0xFFA68C71)
internal val orangeOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val orangeTertiaryDarkMediumContrast = Color(0xFFC0D1A3)
internal val orangeOnTertiaryDarkMediumContrast = Color(0xFF0D1A01)
internal val orangeTertiaryContainerDarkMediumContrast = Color(0xFF86956C)
internal val orangeOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val orangeErrorDarkMediumContrast = Color(0xFFFFD2CC)
internal val orangeOnErrorDarkMediumContrast = Color(0xFF540003)
internal val orangeErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val orangeOnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val orangeBackgroundDarkMediumContrast = Color(0xFF19120C)
internal val orangeOnBackgroundDarkMediumContrast = Color(0xFFEEE0D5)
internal val orangeSurfaceDarkMediumContrast = Color(0xFF19120C)
internal val orangeOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val orangeSurfaceVariantDarkMediumContrast = Color(0xFF504539)
internal val orangeOnSurfaceVariantDarkMediumContrast = Color(0xFFD9C9B9)
internal val orangeOutlineDarkMediumContrast = Color(0xFFB0A092)
internal val orangeOutlineVariantDarkMediumContrast = Color(0xFF8F8174)
internal val orangeScrimDarkMediumContrast = Color(0xFF000000)
internal val orangeInverseSurfaceDarkMediumContrast = Color(0xFFEEE0D5)
internal val orangeInverseOnSurfaceDarkMediumContrast = Color(0xFF2B231D)
internal val orangeInversePrimaryDarkMediumContrast = Color(0xFF6E3E00)
internal val orangeSurfaceDimDarkMediumContrast = Color(0xFF19120C)
internal val orangeSurfaceBrightDarkMediumContrast = Color(0xFF4C433C)
internal val orangeSurfaceContainerLowestDarkMediumContrast = Color(0xFF0F0804)
internal val orangeSurfaceContainerLowDarkMediumContrast = Color(0xFF241C16)
internal val orangeSurfaceContainerDarkMediumContrast = Color(0xFF2F2620)
internal val orangeSurfaceContainerHighDarkMediumContrast = Color(0xFF3A312A)
internal val orangeSurfaceContainerHighestDarkMediumContrast = Color(0xFF453C35)

// --- High Contrast Dark ---
internal val orangePrimaryDarkHighContrast = Color(0xFFFFFAF8)
internal val orangeOnPrimaryDarkHighContrast = Color(0xFF000000)
internal val orangePrimaryContainerDarkHighContrast = Color(0xFFFFC28F)
internal val orangeOnPrimaryContainerDarkHighContrast = Color(0xFF000000)
internal val orangeSecondaryDarkHighContrast = Color(0xFFFFFAF8)
internal val orangeOnSecondaryDarkHighContrast = Color(0xFF000000)
internal val orangeSecondaryContainerDarkHighContrast = Color(0xFFE4C5A7)
internal val orangeOnSecondaryContainerDarkHighContrast = Color(0xFF000000)
internal val orangeTertiaryDarkHighContrast = Color(0xFFF6FFE4)
internal val orangeOnTertiaryDarkHighContrast = Color(0xFF000000)
internal val orangeTertiaryContainerDarkHighContrast = Color(0xFFC0D1A3)
internal val orangeOnTertiaryContainerDarkHighContrast = Color(0xFF000000)
internal val orangeErrorDarkHighContrast = Color(0xFFFFECE9)
internal val orangeOnErrorDarkHighContrast = Color(0xFF000000)
internal val orangeErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val orangeOnErrorContainerDarkHighContrast = Color(0xFF000000)
internal val orangeBackgroundDarkHighContrast = Color(0xFF19120C)
internal val orangeOnBackgroundDarkHighContrast = Color(0xFFEEE0D5)
internal val orangeSurfaceDarkHighContrast = Color(0xFF19120C)
internal val orangeOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val orangeSurfaceVariantDarkHighContrast = Color(0xFF504539)
internal val orangeOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val orangeOutlineDarkHighContrast = Color(0xFFF9E9D9)
internal val orangeOutlineVariantDarkHighContrast = Color(0xFFC1B1A3)
internal val orangeScrimDarkHighContrast = Color(0xFF000000)
internal val orangeInverseSurfaceDarkHighContrast = Color(0xFFEEE0D5)
internal val orangeInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val orangeInversePrimaryDarkHighContrast = Color(0xFF412200)
internal val orangeSurfaceDimDarkHighContrast = Color(0xFF19120C)
internal val orangeSurfaceBrightDarkHighContrast = Color(0xFF584E46)
internal val orangeSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val orangeSurfaceContainerLowDarkHighContrast = Color(0xFF261E18)
internal val orangeSurfaceContainerDarkHighContrast = Color(0xFF372F28)
internal val orangeSurfaceContainerHighDarkHighContrast = Color(0xFF423A33)
internal val orangeSurfaceContainerHighestDarkHighContrast = Color(0xFF4D453E)


// --- Color Scheme Objects ---

internal val OrangeLightColorScheme = lightColorScheme(
    primary = orangePrimaryLight,
    onPrimary = orangeOnPrimaryLight,
    primaryContainer = orangePrimaryContainerLight,
    onPrimaryContainer = orangeOnPrimaryContainerLight,
    secondary = orangeSecondaryLight,
    onSecondary = orangeOnSecondaryLight,
    secondaryContainer = orangeSecondaryContainerLight,
    onSecondaryContainer = orangeOnSecondaryContainerLight,
    tertiary = orangeTertiaryLight,
    onTertiary = orangeOnTertiaryLight,
    tertiaryContainer = orangeTertiaryContainerLight,
    onTertiaryContainer = orangeOnTertiaryContainerLight,
    error = orangeErrorLight,
    onError = orangeOnErrorLight,
    errorContainer = orangeErrorContainerLight,
    onErrorContainer = orangeOnErrorContainerLight,
    background = orangeBackgroundLight,
    onBackground = orangeOnBackgroundLight,
    surface = orangeSurfaceLight,
    onSurface = orangeOnSurfaceLight,
    surfaceVariant = orangeSurfaceVariantLight,
    onSurfaceVariant = orangeOnSurfaceVariantLight,
    outline = orangeOutlineLight,
    outlineVariant = orangeOutlineVariantLight,
    scrim = orangeScrimLight,
    inverseSurface = orangeInverseSurfaceLight,
    inverseOnSurface = orangeInverseOnSurfaceLight,
    inversePrimary = orangeInversePrimaryLight,
    surfaceDim = orangeSurfaceDimLight,
    surfaceBright = orangeSurfaceBrightLight,
    surfaceContainerLowest = orangeSurfaceContainerLowestLight,
    surfaceContainerLow = orangeSurfaceContainerLowLight,
    surfaceContainer = orangeSurfaceContainerLight,
    surfaceContainerHigh = orangeSurfaceContainerHighLight,
    surfaceContainerHighest = orangeSurfaceContainerHighestLight,
)

internal val OrangeDarkColorScheme = darkColorScheme(
    primary = orangePrimaryDark,
    onPrimary = orangeOnPrimaryDark,
    primaryContainer = orangePrimaryContainerDark,
    onPrimaryContainer = orangeOnPrimaryContainerDark,
    secondary = orangeSecondaryDark,
    onSecondary = orangeOnSecondaryDark,
    secondaryContainer = orangeSecondaryContainerDark,
    onSecondaryContainer = orangeOnSecondaryContainerDark,
    tertiary = orangeTertiaryDark,
    onTertiary = orangeOnTertiaryDark,
    tertiaryContainer = orangeTertiaryContainerDark,
    onTertiaryContainer = orangeOnTertiaryContainerDark,
    error = orangeErrorDark,
    onError = orangeOnErrorDark,
    errorContainer = orangeErrorContainerDark,
    onErrorContainer = orangeOnErrorContainerDark,
    background = orangeBackgroundDark,
    onBackground = orangeOnBackgroundDark,
    surface = orangeSurfaceDark,
    onSurface = orangeOnSurfaceDark,
    surfaceVariant = orangeSurfaceVariantDark,
    onSurfaceVariant = orangeOnSurfaceVariantDark,
    outline = orangeOutlineDark,
    outlineVariant = orangeOutlineVariantDark,
    scrim = orangeScrimDark,
    inverseSurface = orangeInverseSurfaceDark,
    inverseOnSurface = orangeInverseOnSurfaceDark,
    inversePrimary = orangeInversePrimaryDark,
    surfaceDim = orangeSurfaceDimDark,
    surfaceBright = orangeSurfaceBrightDark,
    surfaceContainerLowest = orangeSurfaceContainerLowestDark,
    surfaceContainerLow = orangeSurfaceContainerLowDark,
    surfaceContainer = orangeSurfaceContainerDark,
    surfaceContainerHigh = orangeSurfaceContainerHighDark,
    surfaceContainerHighest = orangeSurfaceContainerHighestDark,
)