package com.nguyenminhkhang.compose

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// --- Light Scheme ---
internal val purplePrimaryLight = Color(0xFF6F43C0)
internal val purpleOnPrimaryLight = Color(0xFFFFFFFF)
internal val purplePrimaryContainerLight = Color(0xFFE9DDFF)
internal val purpleOnPrimaryContainerLight = Color(0xFF250059)
internal val purpleSecondaryLight = Color(0xFF625B71)
internal val purpleOnSecondaryLight = Color(0xFFFFFFFF)
internal val purpleSecondaryContainerLight = Color(0xFFE8DEF8)
internal val purpleOnSecondaryContainerLight = Color(0xFF1E192B)
internal val purpleTertiaryLight = Color(0xFF7E5260)
internal val purpleOnTertiaryLight = Color(0xFFFFFFFF)
internal val purpleTertiaryContainerLight = Color(0xFFFFD8E4)
internal val purpleOnTertiaryContainerLight = Color(0xFF31111D)
internal val purpleErrorLight = Color(0xFFBA1A1A)
internal val purpleOnErrorLight = Color(0xFFFFFFFF)
internal val purpleErrorContainerLight = Color(0xFFFFDAD6)
internal val purpleOnErrorContainerLight = Color(0xFF410002)
internal val purpleBackgroundLight = Color(0xFFFFF7FF)
internal val purpleOnBackgroundLight = Color(0xFF1D1B20)
internal val purpleSurfaceLight = Color(0xFFFFF7FF)
internal val purpleOnSurfaceLight = Color(0xFF1D1B20)
internal val purpleSurfaceVariantLight = Color(0xFFE7E0EB)
internal val purpleOnSurfaceVariantLight = Color(0xFF49454E)
internal val purpleOutlineLight = Color(0xFF7A757F)
internal val purpleOutlineVariantLight = Color(0xFFCBC4CF)
internal val purpleScrimLight = Color(0xFF000000)
internal val purpleInverseSurfaceLight = Color(0xFF322F35)
internal val purpleInverseOnSurfaceLight = Color(0xFFF5EFF7)
internal val purpleInversePrimaryLight = Color(0xFFD0BCFF)
internal val purpleSurfaceDimLight = Color(0xFFDED8E0)
internal val purpleSurfaceBrightLight = Color(0xFFFFF7FF)
internal val purpleSurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val purpleSurfaceContainerLowLight = Color(0xFFF8F2FA)
internal val purpleSurfaceContainerLight = Color(0xFFF2ECF4)
internal val purpleSurfaceContainerHighLight = Color(0xFFECE6EE)
internal val purpleSurfaceContainerHighestLight = Color(0xFFE6E1E9)

// --- Medium Contrast Light ---
internal val purplePrimaryLightMediumContrast = Color(0xFF5021A3)
internal val purpleOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val purplePrimaryContainerLightMediumContrast = Color(0xFF8659D8)
internal val purpleOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleSecondaryLightMediumContrast = Color(0xFF464054)
internal val purpleOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleSecondaryContainerLightMediumContrast = Color(0xFF787188)
internal val purpleOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleTertiaryLightMediumContrast = Color(0xFF5F3745)
internal val purpleOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleTertiaryContainerLightMediumContrast = Color(0xFF966877)
internal val purpleOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleErrorLightMediumContrast = Color(0xFF8C0009)
internal val purpleOnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleErrorContainerLightMediumContrast = Color(0xFFDA342E)
internal val purpleOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleBackgroundLightMediumContrast = Color(0xFFFFF7FF)
internal val purpleOnBackgroundLightMediumContrast = Color(0xFF1D1B20)
internal val purpleSurfaceLightMediumContrast = Color(0xFFFFF7FF)
internal val purpleOnSurfaceLightMediumContrast = Color(0xFF121015)
internal val purpleSurfaceVariantLightMediumContrast = Color(0xFFE7E0EB)
internal val purpleOnSurfaceVariantLightMediumContrast = Color(0xFF39353E)
internal val purpleOutlineLightMediumContrast = Color(0xFF55515A)
internal val purpleOutlineVariantLightMediumContrast = Color(0xFF716D76)
internal val purpleScrimLightMediumContrast = Color(0xFF000000)
internal val purpleInverseSurfaceLightMediumContrast = Color(0xFF322F35)
internal val purpleInverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF7)
internal val purpleInversePrimaryLightMediumContrast = Color(0xFFD0BCFF)
internal val purpleSurfaceDimLightMediumContrast = Color(0xFFCCC6CE)
internal val purpleSurfaceBrightLightMediumContrast = Color(0xFFFFF7FF)
internal val purpleSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val purpleSurfaceContainerLowLightMediumContrast = Color(0xFFF8F2FA)
internal val purpleSurfaceContainerLightMediumContrast = Color(0xFFECE6EE)
internal val purpleSurfaceContainerHighLightMediumContrast = Color(0xFFE1DBE3)
internal val purpleSurfaceContainerHighestLightMediumContrast = Color(0xFFD5D0D7)

// --- High Contrast Light ---
internal val purplePrimaryLightHighContrast = Color(0xFF2B0068)
internal val purpleOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val purplePrimaryContainerLightHighContrast = Color(0xFF5021A3)
internal val purpleOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val purpleSecondaryLightHighContrast = Color(0xFF251F33)
internal val purpleOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val purpleSecondaryContainerLightHighContrast = Color(0xFF464054)
internal val purpleOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val purpleTertiaryLightHighContrast = Color(0xFF391724)
internal val purpleOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val purpleTertiaryContainerLightHighContrast = Color(0xFF5F3745)
internal val purpleOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val purpleErrorLightHighContrast = Color(0xFF4E0002)
internal val purpleOnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val purpleErrorContainerLightHighContrast = Color(0xFF8C0009)
internal val purpleOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val purpleBackgroundLightHighContrast = Color(0xFFFFF7FF)
internal val purpleOnBackgroundLightHighContrast = Color(0xFF1D1B20)
internal val purpleSurfaceLightHighContrast = Color(0xFFFFF7FF)
internal val purpleOnSurfaceLightHighContrast = Color(0xFF000000)
internal val purpleSurfaceVariantLightHighContrast = Color(0xFFE7E0EB)
internal val purpleOnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val purpleOutlineLightHighContrast = Color(0xFF2E2A33)
internal val purpleOutlineVariantLightHighContrast = Color(0xFF4B4750)
internal val purpleScrimLightHighContrast = Color(0xFF000000)
internal val purpleInverseSurfaceLightHighContrast = Color(0xFF322F35)
internal val purpleInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val purpleInversePrimaryLightHighContrast = Color(0xFFD0BCFF)
internal val purpleSurfaceDimLightHighContrast = Color(0xFFBEB8C0)
internal val purpleSurfaceBrightLightHighContrast = Color(0xFFFFF7FF)
internal val purpleSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val purpleSurfaceContainerLowLightHighContrast = Color(0xFFF5EFF7)
internal val purpleSurfaceContainerLightHighContrast = Color(0xFFE6E1E9)
internal val purpleSurfaceContainerHighLightHighContrast = Color(0xFFD8D2DA)
internal val purpleSurfaceContainerHighestLightHighContrast = Color(0xFFCCC6CE)

// --- Dark Scheme ---
internal val purplePrimaryDark = Color(0xFFD0BCFF)
internal val purpleOnPrimaryDark = Color(0xFF3D008F)
internal val purplePrimaryContainerDark = Color(0xFF5627A7)
internal val purpleOnPrimaryContainerDark = Color(0xFFE9DDFF)
internal val purpleSecondaryDark = Color(0xFFCCC2DC)
internal val purpleOnSecondaryDark = Color(0xFF332D41)
internal val purpleSecondaryContainerDark = Color(0xFF4A4458)
internal val purpleOnSecondaryContainerDark = Color(0xFFE8DEF8)
internal val purpleTertiaryDark = Color(0xFFEFB8C8)
internal val purpleOnTertiaryDark = Color(0xFF492532)
internal val purpleTertiaryContainerDark = Color(0xFF633B48)
internal val purpleOnTertiaryContainerDark = Color(0xFFFFFFD8E4)
internal val purpleErrorDark = Color(0xFFFFB4AB)
internal val purpleOnErrorDark = Color(0xFF690005)
internal val purpleErrorContainerDark = Color(0xFF93000A)
internal val purpleOnErrorContainerDark = Color(0xFFFFDAD6)
internal val purpleBackgroundDark = Color(0xFF141218)
internal val purpleOnBackgroundDark = Color(0xFFE6E1E9)
internal val purpleSurfaceDark = Color(0xFF141218)
internal val purpleOnSurfaceDark = Color(0xFFE6E1E9)
internal val purpleSurfaceVariantDark = Color(0xFF49454F)
internal val purpleOnSurfaceVariantDark = Color(0xFFCBC4CF)
internal val purpleOutlineDark = Color(0xFF948F99)
internal val purpleOutlineVariantDark = Color(0xFF49454F)
internal val purpleScrimDark = Color(0xFF000000)
internal val purpleInverseSurfaceDark = Color(0xFFE6E1E9)
internal val purpleInverseOnSurfaceDark = Color(0xFF322F35)
internal val purpleInversePrimaryDark = Color(0xFF6F43C0)
internal val purpleSurfaceDimDark = Color(0xFF141218)
internal val purpleSurfaceBrightDark = Color(0xFF3B383E)
internal val purpleSurfaceContainerLowestDark = Color(0xFF0F0D13)
internal val purpleSurfaceContainerLowDark = Color(0xFF1D1B20)
internal val purpleSurfaceContainerDark = Color(0xFF211F24)
internal val purpleSurfaceContainerHighDark = Color(0xFF2B292F)
internal val purpleSurfaceContainerHighestDark = Color(0xFF36343A)

// --- Medium Contrast Dark ---
internal val purplePrimaryDarkMediumContrast = Color(0xFFD7C4FF)
internal val purpleOnPrimaryDarkMediumContrast = Color(0xFF1B0045)
internal val purplePrimaryContainerDarkMediumContrast = Color(0xFF9267E6)
internal val purpleOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val purpleSecondaryDarkMediumContrast = Color(0xFFD1C7E0)
internal val purpleOnSecondaryDarkMediumContrast = Color(0xFF181325)
internal val purpleSecondaryContainerDarkMediumContrast = Color(0xFF958DA6)
internal val purpleOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val purpleTertiaryDarkMediumContrast = Color(0xFFF4BDCC)
internal val purpleOnTertiaryDarkMediumContrast = Color(0xFF2D0E19)
internal val purpleTertiaryContainerDarkMediumContrast = Color(0xFFB48392)
internal val purpleOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val purpleErrorDarkMediumContrast = Color(0xFFFFF9F9)
internal val purpleOnErrorDarkMediumContrast = Color(0xFF370001)
internal val purpleErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val purpleOnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val purpleBackgroundDarkMediumContrast = Color(0xFF141218)
internal val purpleOnBackgroundDarkMediumContrast = Color(0xFFE6E1E9)
internal val purpleSurfaceDarkMediumContrast = Color(0xFF141218)
internal val purpleOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val purpleSurfaceVariantDarkMediumContrast = Color(0xFF49454F)
internal val purpleOnSurfaceVariantDarkMediumContrast = Color(0xFFD0C9D3)
internal val purpleOutlineDarkMediumContrast = Color(0xFFA8A2AC)
internal val purpleOutlineVariantDarkMediumContrast = Color(0xFF88828C)
internal val purpleScrimDarkMediumContrast = Color(0xFF000000)
internal val purpleInverseSurfaceDarkMediumContrast = Color(0xFFE6E1E9)
internal val purpleInverseOnSurfaceDarkMediumContrast = Color(0xFF2B292F)
internal val purpleInversePrimaryDarkMediumContrast = Color(0xFF6F43C0)
internal val purpleSurfaceDimDarkMediumContrast = Color(0xFF141218)
internal val purpleSurfaceBrightDarkMediumContrast = Color(0xFF464349)
internal val purpleSurfaceContainerLowestDarkMediumContrast = Color(0xFF09070C)
internal val purpleSurfaceContainerLowDarkMediumContrast = Color(0xFF1F1D23)
internal val purpleSurfaceContainerDarkMediumContrast = Color(0xFF2A272D)
internal val purpleSurfaceContainerHighDarkMediumContrast = Color(0xFF353238)
internal val purpleSurfaceContainerHighestDarkMediumContrast = Color(0xFF3F3D43)

// --- High Contrast Dark ---
internal val purplePrimaryDarkHighContrast = Color(0xFFF5EFFF)
internal val purpleOnPrimaryDarkHighContrast = Color(0xFF000000)
internal val purplePrimaryContainerDarkHighContrast = Color(0xFFD7C4FF)
internal val purpleOnPrimaryContainerDarkHighContrast = Color(0xFF000000)
internal val purpleSecondaryDarkHighContrast = Color(0xFFF5EFFF)
internal val purpleOnSecondaryDarkHighContrast = Color(0xFF000000)
internal val purpleSecondaryContainerDarkHighContrast = Color(0xFFD1C7E0)
internal val purpleOnSecondaryContainerDarkHighContrast = Color(0xFF000000)
internal val purpleTertiaryDarkHighContrast = Color(0xFFFFF9F9)
internal val purpleOnTertiaryDarkHighContrast = Color(0xFF000000)
internal val purpleTertiaryContainerDarkHighContrast = Color(0xFFF4BDCC)
internal val purpleOnTertiaryContainerDarkHighContrast = Color(0xFF000000)
internal val purpleErrorDarkHighContrast = Color(0xFFFFF9F9)
internal val purpleOnErrorDarkHighContrast = Color(0xFF000000)
internal val purpleErrorContainerDarkHighContrast = Color(0xFFFFBAB1)
internal val purpleOnErrorContainerDarkHighContrast = Color(0xFF000000)
internal val purpleBackgroundDarkHighContrast = Color(0xFF141218)
internal val purpleOnBackgroundDarkHighContrast = Color(0xFFE6E1E9)
internal val purpleSurfaceDarkHighContrast = Color(0xFF141218)
internal val purpleOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val purpleSurfaceVariantDarkHighContrast = Color(0xFF49454F)
internal val purpleOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val purpleOutlineDarkHighContrast = Color(0xFFF5EFFF)
internal val purpleOutlineVariantDarkHighContrast = Color(0xFFD0C9D3)
internal val purpleScrimDarkHighContrast = Color(0xFF000000)
internal val purpleInverseSurfaceDarkHighContrast = Color(0xFFE6E1E9)
internal val purpleInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val purpleInversePrimaryDarkHighContrast = Color(0xFF6F43C0)
internal val purpleSurfaceDimDarkHighContrast = Color(0xFF141218)
internal val purpleSurfaceBrightDarkHighContrast = Color(0xFF514E54)
internal val purpleSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val purpleSurfaceContainerLowDarkHighContrast = Color(0xFF211F24)
internal val purpleSurfaceContainerDarkHighContrast = Color(0xFF322F35)
internal val purpleSurfaceContainerHighDarkHighContrast = Color(0xFF3D3A40)
internal val purpleSurfaceContainerHighestDarkHighContrast = Color(0xFF48454B)


// --- Color Scheme Objects ---

internal val PurpleLightColorScheme = lightColorScheme(
    primary = purplePrimaryLight,
    onPrimary = purpleOnPrimaryLight,
    primaryContainer = purplePrimaryContainerLight,
    onPrimaryContainer = purpleOnPrimaryContainerLight,
    secondary = purpleSecondaryLight,
    onSecondary = purpleOnSecondaryLight,
    secondaryContainer = purpleSecondaryContainerLight,
    onSecondaryContainer = purpleOnSecondaryContainerLight,
    tertiary = purpleTertiaryLight,
    onTertiary = purpleOnTertiaryLight,
    tertiaryContainer = purpleTertiaryContainerLight,
    onTertiaryContainer = purpleOnTertiaryContainerLight,
    error = purpleErrorLight,
    onError = purpleOnErrorLight,
    errorContainer = purpleErrorContainerLight,
    onErrorContainer = purpleOnErrorContainerLight,
    background = purpleBackgroundLight,
    onBackground = purpleOnBackgroundLight,
    surface = purpleSurfaceLight,
    onSurface = purpleOnSurfaceLight,
    surfaceVariant = purpleSurfaceVariantLight,
    onSurfaceVariant = purpleOnSurfaceVariantLight,
    outline = purpleOutlineLight,
    outlineVariant = purpleOutlineVariantLight,
    scrim = purpleScrimLight,
    inverseSurface = purpleInverseSurfaceLight,
    inverseOnSurface = purpleInverseOnSurfaceLight,
    inversePrimary = purpleInversePrimaryLight,
    surfaceDim = purpleSurfaceDimLight,
    surfaceBright = purpleSurfaceBrightLight,
    surfaceContainerLowest = purpleSurfaceContainerLowestLight,
    surfaceContainerLow = purpleSurfaceContainerLowLight,
    surfaceContainer = purpleSurfaceContainerLight,
    surfaceContainerHigh = purpleSurfaceContainerHighLight,
    surfaceContainerHighest = purpleSurfaceContainerHighestLight,
)

internal val PurpleDarkColorScheme = darkColorScheme(
    primary = purplePrimaryDark,
    onPrimary = purpleOnPrimaryDark,
    primaryContainer = purplePrimaryContainerDark,
    onPrimaryContainer = purpleOnPrimaryContainerDark,
    secondary = purpleSecondaryDark,
    onSecondary = purpleOnSecondaryDark,
    secondaryContainer = purpleSecondaryContainerDark,
    onSecondaryContainer = purpleOnSecondaryContainerDark,
    tertiary = purpleTertiaryDark,
    onTertiary = purpleOnTertiaryDark,
    tertiaryContainer = purpleTertiaryContainerDark,
    onTertiaryContainer = purpleOnTertiaryContainerDark,
    error = purpleErrorDark,
    onError = purpleOnErrorDark,
    errorContainer = purpleErrorContainerDark,
    onErrorContainer = purpleOnErrorContainerDark,
    background = purpleBackgroundDark,
    onBackground = purpleOnBackgroundDark,
    surface = purpleSurfaceDark,
    onSurface = purpleOnSurfaceDark,
    surfaceVariant = purpleSurfaceVariantDark,
    onSurfaceVariant = purpleOnSurfaceVariantDark,
    outline = purpleOutlineDark,
    outlineVariant = purpleOutlineVariantDark,
    scrim = purpleScrimDark,
    inverseSurface = purpleInverseSurfaceDark,
    inverseOnSurface = purpleInverseOnSurfaceDark,
    inversePrimary = purpleInversePrimaryDark,
    surfaceDim = purpleSurfaceDimDark,
    surfaceBright = purpleSurfaceBrightDark,
    surfaceContainerLowest = purpleSurfaceContainerLowestDark,
    surfaceContainerLow = purpleSurfaceContainerLowDark,
    surfaceContainer = purpleSurfaceContainerDark,
    surfaceContainerHigh = purpleSurfaceContainerHighDark,
    surfaceContainerHighest = purpleSurfaceContainerHighestDark,
)