package com.nguyenminhkhang.taskmanagement.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color


internal val redPrimaryLight = Color(0xFF8F4C38)
internal val redOnPrimaryLight = Color(0xFFFFFFFF)
internal val redPrimaryContainerLight = Color(0xFFFFDBD1)
internal val redOnPrimaryContainerLight = Color(0xFF723523)
internal val redSecondaryLight = Color(0xFF77574E)
internal val redOnSecondaryLight = Color(0xFFFFFFFF)
internal val redSecondaryContainerLight = Color(0xFFFFDBD1)
internal val redOnSecondaryContainerLight = Color(0xFF5D4037)
internal val redTertiaryLight = Color(0xFF6C5D2F)
internal val redOnTertiaryLight = Color(0xFFFFFFFF)
internal val redTertiaryContainerLight = Color(0xFFF5E1A7)
internal val redOnTertiaryContainerLight = Color(0xFF534619)
internal val redErrorLight = Color(0xFFBA1A1A)
internal val redOnErrorLight = Color(0xFFFFFFFF)
internal val redErrorContainerLight = Color(0xFFFFDAD6)
internal val redOnErrorContainerLight = Color(0xFF93000A)
internal val redBackgroundLight = Color(0xFFFFF8F6)
internal val redOnBackgroundLight = Color(0xFF231917)
internal val redSurfaceLight = Color(0xFFFFF8F6)
internal val redOnSurfaceLight = Color(0xFF231917)
internal val redSurfaceVariantLight = Color(0xFFF5DED8)
internal val redOnSurfaceVariantLight = Color(0xFF53433F)
internal val redOutlineLight = Color(0xFF85736E)
internal val redOutlineVariantLight = Color(0xFFD8C2BC)
internal val redScrimLight = Color(0xFF000000)
internal val redInverseSurfaceLight = Color(0xFF392E2B)
internal val redInverseOnSurfaceLight = Color(0xFFFFEDE8)
internal val redInversePrimaryLight = Color(0xFFFFB5A0)
internal val redSurfaceDimLight = Color(0xFFE8D6D2)
internal val redSurfaceBrightLight = Color(0xFFFFF8F6)
internal val redSurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val redSurfaceContainerLowLight = Color(0xFFFFF1ED)
internal val redSurfaceContainerLight = Color(0xFFFCEAE5)
internal val redSurfaceContainerHighLight = Color(0xFFF7E4E0)
internal val redSurfaceContainerHighestLight = Color(0xFFF1DFDA)

internal val redPrimaryLightMediumContrast = Color(0xFF5D2514)
internal val redOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
internal val redPrimaryContainerLightMediumContrast = Color(0xFFA15A45)
internal val redOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val redSecondaryLightMediumContrast = Color(0xFF4B2F28)
internal val redOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
internal val redSecondaryContainerLightMediumContrast = Color(0xFF87655C)
internal val redOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val redTertiaryLightMediumContrast = Color(0xFF41350A)
internal val redOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
internal val redTertiaryContainerLightMediumContrast = Color(0xFF7B6C3C)
internal val redOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val redErrorLightMediumContrast = Color(0xFF740006)
internal val redOnErrorLightMediumContrast = Color(0xFFFFFFFF)
internal val redErrorContainerLightMediumContrast = Color(0xFFCF2C27)
internal val redOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
internal val redBackgroundLightMediumContrast = Color(0xFFFFF8F6)
internal val redOnBackgroundLightMediumContrast = Color(0xFF231917)
internal val redSurfaceLightMediumContrast = Color(0xFFFFF8F6)
internal val redOnSurfaceLightMediumContrast = Color(0xFF180F0D)
internal val redSurfaceVariantLightMediumContrast = Color(0xFFF5DED8)
internal val redOnSurfaceVariantLightMediumContrast = Color(0xFF41332F)
internal val redOutlineLightMediumContrast = Color(0xFF5F4F4A)
internal val redOutlineVariantLightMediumContrast = Color(0xFF7B6964)
internal val redScrimLightMediumContrast = Color(0xFF000000)
internal val redInverseSurfaceLightMediumContrast = Color(0xFF392E2B)
internal val redInverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE8)
internal val redInversePrimaryLightMediumContrast = Color(0xFFFFB5A0)
internal val redSurfaceDimLightMediumContrast = Color(0xFFD4C3BE)
internal val redSurfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
internal val redSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
internal val redSurfaceContainerLowLightMediumContrast = Color(0xFFFFF1ED)
internal val redSurfaceContainerLightMediumContrast = Color(0xFFF7E4E0)
internal val redSurfaceContainerHighLightMediumContrast = Color(0xFFEBD9D4)
internal val redSurfaceContainerHighestLightMediumContrast = Color(0xFFDFCEC9)

internal val redPrimaryLightHighContrast = Color(0xFF501B0B)
internal val redOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val redPrimaryContainerLightHighContrast = Color(0xFF753725)
internal val redOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val redSecondaryLightHighContrast = Color(0xFF3F261E)
internal val redOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val redSecondaryContainerLightHighContrast = Color(0xFF60423A)
internal val redOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val redTertiaryLightHighContrast = Color(0xFF362B02)
internal val redOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val redTertiaryContainerLightHighContrast = Color(0xFF55481C)
internal val redOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val redErrorLightHighContrast = Color(0xFF600004)
internal val redOnErrorLightHighContrast = Color(0xFFFFFFFF)
internal val redErrorContainerLightHighContrast = Color(0xFF98000A)
internal val redOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val redBackgroundLightHighContrast = Color(0xFFFFF8F6)
internal val redOnBackgroundLightHighContrast = Color(0xFF231917)
internal val redSurfaceLightHighContrast = Color(0xFFFFF8F6)
internal val redOnSurfaceLightHighContrast = Color(0xFF000000)
internal val redSurfaceVariantLightHighContrast = Color(0xFFF5DED8)
internal val redOnSurfaceVariantLightHighContrast = Color(0xFF000000)
internal val redOutlineLightHighContrast = Color(0xFF372925)
internal val redOutlineVariantLightHighContrast = Color(0xFF554641)
internal val redScrimLightHighContrast = Color(0xFF000000)
internal val redInverseSurfaceLightHighContrast = Color(0xFF392E2B)
internal val redInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
internal val redInversePrimaryLightHighContrast = Color(0xFFFFB5A0)
internal val redSurfaceDimLightHighContrast = Color(0xFFC6B5B1)
internal val redSurfaceBrightLightHighContrast = Color(0xFFFFF8F6)
internal val redSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
internal val redSurfaceContainerLowLightHighContrast = Color(0xFFFFEDE8)
internal val redSurfaceContainerLightHighContrast = Color(0xFFF1DFDA)
internal val redSurfaceContainerHighLightHighContrast = Color(0xFFE2D1CC)
internal val redSurfaceContainerHighestLightHighContrast = Color(0xFFD4C3BE)

internal val redPrimaryDark = Color(0xFFFFB5A0)
internal val redOnPrimaryDark = Color(0xFF561F0F)
internal val redPrimaryContainerDark = Color(0xFF723523)
internal val redOnPrimaryContainerDark = Color(0xFFFFDBD1)
internal val redSecondaryDark = Color(0xFFE7BDB2)
internal val redOnSecondaryDark = Color(0xFF442A22)
internal val redSecondaryContainerDark = Color(0xFF5D4037)
internal val redOnSecondaryContainerDark = Color(0xFFFFDBD1)
internal val redTertiaryDark = Color(0xFFD8C58D)
internal val redOnTertiaryDark = Color(0xFF3B2F05)
internal val redTertiaryContainerDark = Color(0xFF534619)
internal val redOnTertiaryContainerDark = Color(0xFFF5E1A7)
internal val redErrorDark = Color(0xFFFFB4AB)
internal val redOnErrorDark = Color(0xFF690005)
internal val redErrorContainerDark = Color(0xFF93000A)
internal val redOnErrorContainerDark = Color(0xFFFFDAD6)
internal val redBackgroundDark = Color(0xFF1A110F)
internal val redOnBackgroundDark = Color(0xFFF1DFDA)
internal val redSurfaceDark = Color(0xFF1A110F)
internal val redOnSurfaceDark = Color(0xFFF1DFDA)
internal val redSurfaceVariantDark = Color(0xFF53433F)
internal val redOnSurfaceVariantDark = Color(0xFFD8C2BC)
internal val redOutlineDark = Color(0xFFA08C87)
internal val redOutlineVariantDark = Color(0xFF53433F)
internal val redScrimDark = Color(0xFF000000)
internal val redInverseSurfaceDark = Color(0xFFF1DFDA)
internal val redInverseOnSurfaceDark = Color(0xFF392E2B)
internal val redInversePrimaryDark = Color(0xFF8F4C38)
internal val redSurfaceDimDark = Color(0xFF1A110F)
internal val redSurfaceBrightDark = Color(0xFF423734)
internal val redSurfaceContainerLowestDark = Color(0xFF140C0A)
internal val redSurfaceContainerLowDark = Color(0xFF231917)
internal val redSurfaceContainerDark = Color(0xFF271D1B)
internal val redSurfaceContainerHighDark = Color(0xFF322825)
internal val redSurfaceContainerHighestDark = Color(0xFF3D322F)

internal val redPrimaryDarkMediumContrast = Color(0xFFFFD2C6)
internal val redOnPrimaryDarkMediumContrast = Color(0xFF481506)
internal val redPrimaryContainerDarkMediumContrast = Color(0xFFCB7C65)
internal val redOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
internal val redSecondaryDarkMediumContrast = Color(0xFFFED3C7)
internal val redOnSecondaryDarkMediumContrast = Color(0xFF381F18)
internal val redSecondaryContainerDarkMediumContrast = Color(0xFFAE887E)
internal val redOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
internal val redTertiaryDarkMediumContrast = Color(0xFFEFDBA1)
internal val redOnTertiaryDarkMediumContrast = Color(0xFF2F2500)
internal val redTertiaryContainerDarkMediumContrast = Color(0xFFA0905C)
internal val redOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
internal val redErrorDarkMediumContrast = Color(0xFFFFD2CC)
internal val redOnErrorDarkMediumContrast = Color(0xFF540003)
internal val redErrorContainerDarkMediumContrast = Color(0xFFFF5449)
internal val redOnErrorContainerDarkMediumContrast = Color(0xFF000000)
internal val redBackgroundDarkMediumContrast = Color(0xFF1A110F)
internal val redOnBackgroundDarkMediumContrast = Color(0xFFF1DFDA)
internal val redSurfaceDarkMediumContrast = Color(0xFF1A110F)
internal val redOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
internal val redSurfaceVariantDarkMediumContrast = Color(0xFF53433F)
internal val redOnSurfaceVariantDarkMediumContrast = Color(0xFFEED7D1)
internal val redOutlineDarkMediumContrast = Color(0xFFC2ADA8)
internal val redOutlineVariantDarkMediumContrast = Color(0xFFA08C87)
internal val redScrimDarkMediumContrast = Color(0xFF000000)
internal val redInverseSurfaceDarkMediumContrast = Color(0xFFF1DFDA)
internal val redInverseOnSurfaceDarkMediumContrast = Color(0xFF322825)
internal val redInversePrimaryDarkMediumContrast = Color(0xFF743624)
internal val redSurfaceDimDarkMediumContrast = Color(0xFF1A110F)
internal val redSurfaceBrightDarkMediumContrast = Color(0xFF4E423F)
internal val redSurfaceContainerLowestDarkMediumContrast = Color(0xFF0D0604)
internal val redSurfaceContainerLowDarkMediumContrast = Color(0xFF251B19)
internal val redSurfaceContainerDarkMediumContrast = Color(0xFF302623)
internal val redSurfaceContainerHighDarkMediumContrast = Color(0xFF3B302D)
internal val redSurfaceContainerHighestDarkMediumContrast = Color(0xFF463B38)

internal val redPrimaryDarkHighContrast = Color(0xFFFFECE7)
internal val redOnPrimaryDarkHighContrast = Color(0xFF000000)
internal val redPrimaryContainerDarkHighContrast = Color(0xFFFFAF98)
internal val redOnPrimaryContainerDarkHighContrast = Color(0xFF1E0300)
internal val redSecondaryDarkHighContrast = Color(0xFFFFECE7)
internal val redOnSecondaryDarkHighContrast = Color(0xFF000000)
internal val redSecondaryContainerDarkHighContrast = Color(0xFFE3B9AE)
internal val redOnSecondaryContainerDarkHighContrast = Color(0xFF190603)
internal val redTertiaryDarkHighContrast = Color(0xFFFFEFC4)
internal val redOnTertiaryDarkHighContrast = Color(0xFF000000)
internal val redTertiaryContainerDarkHighContrast = Color(0xFFD4C289)
internal val redOnTertiaryContainerDarkHighContrast = Color(0xFF100B00)
internal val redErrorDarkHighContrast = Color(0xFFFFECE9)
internal val redOnErrorDarkHighContrast = Color(0xFF000000)
internal val redErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
internal val redOnErrorContainerDarkHighContrast = Color(0xFF220001)
internal val redBackgroundDarkHighContrast = Color(0xFF1A110F)
internal val redOnBackgroundDarkHighContrast = Color(0xFFF1DFDA)
internal val redSurfaceDarkHighContrast = Color(0xFF1A110F)
internal val redOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val redSurfaceVariantDarkHighContrast = Color(0xFF53433F)
internal val redOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
internal val redOutlineDarkHighContrast = Color(0xFFFFECE7)
internal val redOutlineVariantDarkHighContrast = Color(0xFFD4BEB8)
internal val redScrimDarkHighContrast = Color(0xFF000000)
internal val redInverseSurfaceDarkHighContrast = Color(0xFFF1DFDA)
internal val redInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
internal val redInversePrimaryDarkHighContrast = Color(0xFF743624)
internal val redSurfaceDimDarkHighContrast = Color(0xFF1A110F)
internal val redSurfaceBrightDarkHighContrast = Color(0xFF5A4D4A)
internal val redSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
internal val redSurfaceContainerLowDarkHighContrast = Color(0xFF271D1B)
internal val redSurfaceContainerDarkHighContrast = Color(0xFF392E2B)
internal val redSurfaceContainerHighDarkHighContrast = Color(0xFF443936)
internal val redSurfaceContainerHighestDarkHighContrast = Color(0xFF504441)









internal val RedLightColorScheme = lightColorScheme(

    primary = redPrimaryLight,
    onPrimary = redOnPrimaryLight,
    primaryContainer = redPrimaryContainerLight,
    onPrimaryContainer = redOnPrimaryContainerLight,
    secondary = redSecondaryLight,
    onSecondary = redOnSecondaryLight,
    secondaryContainer = redSecondaryContainerLight,
    onSecondaryContainer = redOnSecondaryContainerLight,
    tertiary = redTertiaryLight,
    onTertiary = redOnTertiaryLight,
    tertiaryContainer = redTertiaryContainerLight,
    onTertiaryContainer = redOnTertiaryContainerLight,
    error = redErrorLight,
    onError = redOnErrorLight,
    errorContainer = redErrorContainerLight,
    onErrorContainer = redOnErrorContainerLight,
    background = redBackgroundLight,
    onBackground = redOnBackgroundLight,
    surface = redSurfaceLight,
    onSurface = redOnSurfaceLight,
    surfaceVariant = redSurfaceVariantLight,
    onSurfaceVariant = redOnSurfaceVariantLight,
    outline = redOutlineLight,
    outlineVariant = redOutlineVariantLight,
    scrim = redScrimLight,
    inverseSurface = redInverseSurfaceLight,
    inverseOnSurface = redInverseOnSurfaceLight,
    inversePrimary = redInversePrimaryLight,
    surfaceDim = redSurfaceDimLight,
    surfaceBright = redSurfaceBrightLight,
    surfaceContainerLowest = redSurfaceContainerLowestLight,
    surfaceContainerLow = redSurfaceContainerLowLight,
    surfaceContainer = redSurfaceContainerLight,
    surfaceContainerHigh = redSurfaceContainerHighLight,
    surfaceContainerHighest = redSurfaceContainerHighestLight,

)

internal val RedDarkColorScheme = darkColorScheme(

    primary = redPrimaryDark,
    onPrimary = redOnPrimaryDark,
    primaryContainer = redPrimaryContainerDark,
    onPrimaryContainer = redOnPrimaryContainerDark,
    secondary = redSecondaryDark,
    onSecondary = redOnSecondaryDark,
    secondaryContainer = redSecondaryContainerDark,
    onSecondaryContainer = redOnSecondaryContainerDark,
    tertiary = redTertiaryDark,
    onTertiary = redOnTertiaryDark,
    tertiaryContainer = redTertiaryContainerDark,
    onTertiaryContainer = redOnTertiaryContainerDark,
    error = redErrorDark,
    onError = redOnErrorDark,
    errorContainer = redErrorContainerDark,
    onErrorContainer = redOnErrorContainerDark,
    background = redBackgroundDark,
    onBackground = redOnBackgroundDark,
    surface = redSurfaceDark,
    onSurface = redOnSurfaceDark,
    surfaceVariant = redSurfaceVariantDark,
    onSurfaceVariant = redOnSurfaceVariantDark,
    outline = redOutlineDark,
    outlineVariant = redOutlineVariantDark,
    scrim = redScrimDark,
    inverseSurface = redInverseSurfaceDark,
    inverseOnSurface = redInverseOnSurfaceDark,
    inversePrimary = redInversePrimaryDark,
    surfaceDim = redSurfaceDimDark,
    surfaceBright = redSurfaceBrightDark,
    surfaceContainerLowest = redSurfaceContainerLowestDark,
    surfaceContainerLow = redSurfaceContainerLowDark,
    surfaceContainer = redSurfaceContainerDark,
    surfaceContainerHigh = redSurfaceContainerHighDark,
    surfaceContainerHighest = redSurfaceContainerHighestDark,

)
